apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: camden
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  spring.datasource.password: cGFzc3dvcmQ=
  password: cGFzc3dvcmQ=
